### PR TITLE
Broken sessions fix

### PR DESCRIPTION
**Pull request by wvdongen**
Make sure CakeSession is used, otherwise CakePHP sessions will be ignored because the Facebook vendor lib will start a basic PHP session first.

### CODE REVIEW

**Comment by wvdongen** [comment]
To clarify this issue, see this commit https://github.com/webtechnick/CakePHP-Facebook-Plugin/commit/da0d300a5a7ab39c0da81b1a43aca764ba6472f2. It fixes the same issue. However, the Facebook SDK update after that commit have undone the fix. So the fix, which is not present anymore,  was not correctly placed because it is undone after every SDK update.

**Comment by webtechnick** [comment]
This is solved in the latest version. Please update your master repository.

**Comment by wvdongen** [comment]
You fixed it in the wrong place. With every SDK update you will undo this fix. When you place the CakeSession start like it is in my commit, session _start() in the SDK will never run due to the if statements around it.

**Comment by webtechnick** [comment]
That fix doesn't work. It still throws the same error. I'm well aware I will have to alter the SDK every update.

**Pull request closed without merging**
